-- Create bucket for dispute evidence
insert into storage.buckets (id, name, public)
values ('dispute-evidence', 'dispute-evidence', false);

-- Policy: Authenticated users can upload evidence
create policy "Users can upload dispute evidence"
on storage.objects for insert
with check (
  bucket_id = 'dispute-evidence' AND
  auth.role() = 'authenticated'
);

-- Policy: Admin can view all, Users can view their own or if they are the transaction counterparty
-- This is complex in storage policies. Simplified: Users can view objects they uploaded. 
-- Realistically, allow auth users to view for now if they have the UUID (security by obscurity + signed URLs preferable but complex for this MVP).
-- Let's stick to: Users can select their own.
create policy "Users can view own evidence"
on storage.objects for select
using (
  bucket_id = 'dispute-evidence' AND
  auth.uid() = owner
);

-- Note: To show evidence to the other party, we should use Signed URLs generated by the server.
